### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#11]
Before we release it to npm we should rename it to `deltachat-node`.

**Comment by Jikstra** [comment]
Yes. We maybe should leave the old repo their until we implemented every bit of it. As soon as we have this, we can safely delete it i guess and take over it's name.

**Comment by ralphtheninja** [comment]
> Yes. We maybe should leave the old repo their until we implemented every bit of it. As soon as we have this, we can safely delete it i guess and take over it's name.

The old repo can still exist and be around, but we can rename that to something like `deltachat-node-legacy` or something.

I want to get this out on npm as quickly as possible with a minimal api, so removing `1.0.0` milestone.

**Comment by ralphtheninja** [comment]
Done.
